Add SVG validation
MetaMask/snaps pull request #1401
Opened 2023-05-15 14:24 UTC by FrederikBolding

Adds validation of the snap SVG icon.

Fixes #1397

2023-05-16 12:21 UTC, ritave commented
Is this necessary? I would be ok with accepting .pngs and .jpgs, etc.

URLs and especially dataurls are not safe, but I don't see why not all local images.

2023-05-16 12:26 UTC, FrederikBolding commented
> Is this necessary? I would be ok with accepting .pngs and .jpgs, etc.
> 
> URLs and especially dataurls are not safe, but I don't see why not all local images.

Hmm, the spec specifically says SVGs and everything is currently built in a way that only supports SVG. However, there is no check to determine if an icon is actually an SVG, so weird errors may occur when using non SVGs.

If we want to support non-SVGs we would have to spend some time getting that working across the platform and in the extension. We can do that if we want to, but I'm not sure if there are more security concerns with loading arbitrary files instead of SVG? I'm not sure why SVG was chosen originally.

2023-05-16 12:31 UTC, ritave commented
> I'm not sure why SVG was chosen originally.
IIRC for ease of implementation

> so weird errors may occur when using non SVGs.
The end is `<img src={} />` react component, so it should work out of the box, the only places it might break is when we're operating on the npm package or manifest. I think people were already using pngs without problems at this point?

In any case, doesn't need to be before audit, but it could be.

2023-05-24 09:22 UTC, FrederikBolding commented
> The end is `<img src={} />` React component, so it should work out of the box, the only places it might break is when we're operating on the npm package or manifest. I think people were already using pngs without problems at this point?

This is not the case, we expect SVGs in the extension and format the `src` property as such: https://github.com/MetaMask/metamask-extension/blob/832ce634fd4b2b09b3a33911852fd851d82a373e/ui/selectors/selectors.js#L634-L636

There may be other cases such as this, currently anything binary will probably break.

2023-05-24 09:23 UTC, FrederikBolding commented on packages/snaps-utils/src/icon.test.ts
> +    expect(() => assertIsSnapIcon(icon)).toThrow(
Yeah, that's a good idea. I'll wait till the discussion with Olaf wraps up though to not waste further time on this if we don't want to pursue it.

2023-05-26 09:58 UTC, FrederikBolding commented on packages/snaps-utils/src/icon.test.ts
> +    expect(() => assertIsSnapIcon(icon)).toThrow(
Done!

2023-05-26 10:08 UTC, FrederikBolding commented
@SocketSecurity ignore-all

2023-05-26 10:19 UTC, Mrtenz requested changes

2023-05-26 10:19 UTC, Mrtenz commented on packages/snaps-utils/src/icon.ts
> +  assert(icon.path.endsWith('.svg'), 'Expected snap icon to end in .svg');
```suggestion
  assert(icon.path.endsWith('.svg'), 'Expected snap icon to end in ".svg".');
```

2023-05-26 10:19 UTC, Mrtenz commented on packages/snaps-utils/src/icon.ts
> +  assert(isSvg(icon.toString()), 'Snap icon must be a valid SVG');
```suggestion
  assert(isSvg(icon.toString()), 'Snap icon must be a valid SVG.');
```

2023-05-26 10:22 UTC, Mrtenz submitted a review, later dismissed

2023-05-26 10:52 UTC, Mrtenz approved these changes

2023-05-26 11:36 UTC, merged