correct curve name in snap_getBip32PublicKey
MetaMask/snaps pull request #1651
Opened 2023-07-29 16:35 UTC by ducnbh

2023-07-29 19:46 UTC, hmalik88 approved these changes

2023-07-29 20:08 UTC, hmalik88 requested changes
Good catch @ducnbh, do you mind adding a test?

2023-07-30 10:09 UTC, ducnbh commented
hi @hmalik88 , when trying to use with value `ed25519`, I got the following issue from `key-tree` , can you help to confirm whether it does't support `ed25519` anymore ?
![image](https://github.com/MetaMask/snaps/assets/30291474/83aed811-6d08-43ca-841f-12ccedf7ce1f)

2023-08-21 15:24 UTC, hmalik88 commented
Closing in favor of #1678

2023-08-21 15:24 UTC, closed without merging