Update transaction insight response and add severity level enum
MetaMask/snaps pull request #1653
Opened 2023-07-31 17:48 UTC by hmalik88

Closes #1652

2023-08-04 09:13 UTC, Mrtenz requested changes

2023-08-04 09:13 UTC, Mrtenz commented on packages/snaps-utils/src/handlers.ts
> +  severity?: SeverityLevel;
Should be wrapped in `EnumToUnion` (so you can use both `'critical'` and `SeverityLevel.Critical`).

2023-08-04 09:13 UTC, Mrtenz commented on packages/snaps-utils/src/handlers.ts
> +export enum SeverityLevel {
Should be re-exported from `snaps-types`.

2023-08-16 09:23 UTC, FrederikBolding requested changes

2023-08-16 09:23 UTC, FrederikBolding commented on packages/snaps-types/src/types.ts
> +  SeverityLevel,
Needs to not be a type export since it is an enum

2023-08-18 11:26 UTC, FrederikBolding approved these changes

2023-08-18 11:53 UTC, FrederikBolding submitted a review, later dismissed

2023-08-18 13:40 UTC, FrederikBolding approved these changes

2023-08-18 13:48 UTC, merged