Add static file API
MetaMask/snaps pull request #1836
Opened 2023-10-10 11:57 UTC by FrederikBolding

Adds an API for snaps to access auxiliary files at runtime.

WIP

Fixes https://github.com/MetaMask/snaps/issues/1778

2023-10-11 10:01 UTC, Mrtenz requested changes
Looks great overall. One thing to consider is that something like `base64` has a higher information density than `base16` (hexadecimal). We should test the performance difference when loading large files between those two.

2023-10-11 10:16 UTC, FrederikBolding commented on packages/snaps-utils/src/manifest/manifest.ts
> +): Promise<VirtualFile[] | undefined> {
I think all of this logic in `manifest.ts` deserves a refactor. For now this is intended to mirror the other implementations

2023-10-11 10:18 UTC, FrederikBolding commented on packages/examples/packages/get-file/README.md
> +a static file during runtime in your snap.
We'll need to update this in all the examples 😅

2023-10-11 10:19 UTC, Mrtenz commented on packages/examples/packages/get-file/README.md
> +a static file during runtime in your snap.
Yeah. Not in this PR though.

2023-10-11 10:20 UTC, FrederikBolding commented on packages/examples/packages/get-file/README.md
> +"source": {
What do you mean?

2023-10-11 10:22 UTC, Mrtenz commented on packages/examples/packages/get-file/README.md
> +"source": {
Sorry I meant indentation

2023-10-11 10:23 UTC, FrederikBolding commented on packages/examples/packages/get-file/README.md
> +a static file during runtime in your snap.
Can we do them all at once?

2023-10-11 10:26 UTC, FrederikBolding commented on packages/examples/packages/get-file/README.md
> +"source": {
Attempted to fix

2023-10-16 08:24 UTC, Mrtenz commented on packages/rpc-methods/src/permitted/getFile.ts
> +}
I would probably make this a union instead of an enum.

2023-10-16 08:51 UTC, Mrtenz commented on packages/snaps-utils/src/auxiliaryFiles.ts
`auxiliary-files.ts` for consistency?

2023-10-16 08:54 UTC, FrederikBolding commented on packages/snaps-utils/src/auxiliaryFiles.ts
Sure!

2023-10-16 10:03 UTC, Mrtenz requested changes

2023-10-16 10:03 UTC, Mrtenz commented on packages/snaps-simulator/src/features/simulation/hooks.ts
> +  }
```suggestion

  if (!base64) {
    return null;
  }

```

2023-10-16 10:22 UTC, Mrtenz approved these changes

2023-10-16 10:36 UTC, merged