Fix URL not being passed entirely in `assertLinksAreSafe`
MetaMask/snaps pull request #1914
Opened 2023-11-02 10:39 UTC by GuillaumeRx

2023-11-02 10:40 UTC, GuillaumeRx commented
@metamaskbot publish-preview

2023-11-02 10:48 UTC, Mrtenz requested changes
Please add a PR description as well.

2023-11-02 10:48 UTC, Mrtenz commented on packages/snaps-ui/src/validation.ts
> +            : url.toString();
Please add a test to make sure that the behaviour is now correct.

2023-11-09 14:04 UTC, GuillaumeRx commented
@metamaskbot publish-preview

2023-11-15 15:03 UTC, FrederikBolding commented on packages/snaps-utils/src/ui.ts
> + * Searches for markdown links in a sting and checks them against the phishing list.
```suggestion
 * Searches for markdown links in a string and checks them against the phishing list.
```

2023-11-15 15:10 UTC, FrederikBolding commented on packages/snaps-utils/src/ui.ts
> +      if (link) {
Could we rewrite to reduce the nesting? It's a bit difficult to read now.

Can probably be done with 
```js
if (!link) {
  continue;
}
```

or a filter on the `matches`?

2023-11-15 15:30 UTC, FrederikBolding commented on packages/snaps-utils/src/ui.ts
> +  if (matches) {
Maybe we can unnest here too?

```js
if (!matches) {
  return;
}
```

What do you think?

2023-11-15 15:31 UTC, FrederikBolding commented on packages/snaps-utils/src/ui.ts
> +const MARKDOWN_LINK_REGEX = /!?\[(?<name>[^\]]*)\]\((?<url>[^)]+)\)/giu;
Why do we need the `!?` in this regex?

2023-11-15 15:34 UTC, GuillaumeRx commented on packages/snaps-utils/src/ui.ts
> +const MARKDOWN_LINK_REGEX = /!?\[(?<name>[^\]]*)\]\((?<url>[^)]+)\)/giu;
Yeah, it's not needed. Good catch

2023-11-15 15:44 UTC, FrederikBolding approved these changes

2023-11-15 16:02 UTC, merged