feat: Implement `MultichainRouter` and `onProtocolRequest` (SIP-26)
MetaMask/snaps pull request #2875
Opened 2024-11-05 13:58 UTC by FrederikBolding

This PR adds a `MultichainRouter` that can handle routing of non-EVM requests received via the multichain API. The multichain API should integrate this by calling `MultichainRouter.handleRequest` for any requests that are not understood by our existing JSON-RPC stack.

Additionally this PR implements `onProtocolRequest`, a new handler that Snaps can choose to register if they want to service protocol (non signing) requests for a given set of methods for one or more chains. The endowment is registered as follows:
```json5
"initialPermissions": {
  "endowment:protocol": {
    "scopes": {
      "<caip2_chainId>": {
        "methods": [
          // List of supported methods
        ],
        "notifications": [
          // List of supported notifications
        ]
      }
    }
  }
}
```

This implementation follows https://metamask.github.io/SIPs/SIPS/sip-26

Closes https://github.com/MetaMask/snaps/issues/2898

2025-01-29 10:33 UTC, Mrtenz requested changes

2025-01-29 10:33 UTC, Mrtenz commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      );
Nit for readability:
```suggestion
      );

```

2025-01-29 10:33 UTC, Mrtenz commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +    );
Nit:
```suggestion
    );

```

2025-01-29 10:33 UTC, Mrtenz commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +    );
```suggestion
    );

```

2025-01-29 10:33 UTC, Mrtenz commented on packages/snaps-execution-environments/src/common/validation.ts
> +}) as unknown as Struct<{ scope: CaipChainId; request: JsonRpcRequest }, null>;
What's the reason for this?

2025-01-29 10:34 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +export class MultichainRouter {
Originally it did, but it doesn't store any state, so it seems unnecessary. Basically following the same pattern as the execution services that register themselves on the messenger without being controllers

2025-01-29 11:00 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      throw rpcErrors.invalidParams();
Any proposals? 😄

2025-01-29 11:01 UTC, FrederikBolding commented on packages/snaps-execution-environments/src/common/validation.ts
> +}) as unknown as Struct<{ scope: CaipChainId; request: JsonRpcRequest }, null>;
`The inferred type of 'OnProtocolRequestArgumentsStruct' references an inaccessible 'unique symbol' type. A type annotation is necessary.`

2025-01-29 11:01 UTC, FrederikBolding commented on packages/snaps-execution-environments/src/common/validation.ts
> +}) as unknown as Struct<{ scope: CaipChainId; request: JsonRpcRequest }, null>;
And casting without unknown blows up due to the JSON types

2025-01-29 11:01 UTC, Mrtenz commented on packages/snaps-execution-environments/src/common/validation.ts
> +}) as unknown as Struct<{ scope: CaipChainId; request: JsonRpcRequest }, null>;
Is it not exported?

2025-01-29 11:02 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +    })[];
Done!

2025-01-29 11:02 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +  async #resolveRequestAddress(
Added!

2025-01-29 11:04 UTC, FrederikBolding commented on packages/snaps-execution-environments/src/common/validation.ts
> +}) as unknown as Struct<{ scope: CaipChainId; request: JsonRpcRequest }, null>;
guess not 🤷‍♂️ https://github.com/MetaMask/utils/blob/90837bad1d85277aa5b8f16fe40beb81e0a1e09d/src/json.ts#L94

2025-01-29 11:58 UTC, Mrtenz commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      throw rpcErrors.invalidParams();
"Unable to get selected account" or something?

2025-01-29 13:11 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      throw rpcErrors.invalidParams();
Done!

2025-01-29 13:16 UTC, Mrtenz submitted a review, later dismissed

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      .call('AccountsController:listMultichainAccounts', scope)
Note for us @danroc.

This method relies on a old logic (prior to the `scopes` introduction), and we should definitely update this now, see:
- https://github.com/MetaMask/core/blob/v290.0.0/packages/accounts-controller/src/AccountsController.ts#L1044-L1046

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-controllers/src/test-utils/multichain.ts
> +  'bip122:000000000019d6689c085ae165831e93' as CaipChainId;
Nit: We also have some defined scopes in the `keyring-api` now (in case you'd like to use them):
- https://github.com/MetaMask/accounts/blob/main/packages/keyring-api/src/btc/constants.ts#L6-L12

NOTE: Since CAIP is becoming quite present everywhere now, I wonder if there would be a better place to put those kind of constant, the keyring API does feel always appropriate... and I don't think `@metamask/utils` is a good fit either. Anyway, topic for later 🙃

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-execution-environments/src/common/validation.test.ts
> +      request: {
Nit:
```suggestion
      // Missing `scopes`
      request: {
```

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-execution-environments/src/common/validation.test.ts
> +      scope: 'foo',
Nit:

```suggestion
      // Invalid `scopes`
      scope: 'foo',
```

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-execution-environments/src/common/validation.test.ts
> +    { request: { foo: 'bar' } },
Nit:

```suggestion
    {
      // Invalid `JsonRpcRequest`
      request: {
        foo: 'bar'
      }
    },
```

2025-01-31 12:19 UTC, ccharly commented on packages/snaps-controllers/src/test-utils/multichain.ts
> +    methods: ['btc_sendmany'],
Nit: We renamed it to `sendBitcoin` now: https://github.com/MetaMask/accounts/blob/main/packages/keyring-api/src/btc/types.ts#L39

```suggestion
    methods: ['sendBitcoin'],
```

2025-01-31 12:29 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      .call('AccountsController:listMultichainAccounts', scope)
Definitely agreed. The router assumes this call uses the scopes as much as possible 😄

2025-01-31 12:31 UTC, FrederikBolding commented on packages/snaps-controllers/src/test-utils/multichain.ts
> +  'bip122:000000000019d6689c085ae165831e93' as CaipChainId;
IMO not that important for testing purposes, but I agree they could be moved to utils and used easier here. I don't think bringing in the `keyring-api` here is appropriate.

2025-01-31 12:34 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      )) as { address: CaipAccountId } | null;
Definitely!

2025-01-31 12:35 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +    scope: Caip2ChainId;
Yep - wasn't intentional to mix them

2025-01-31 12:35 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +};
I think this is preferable for now to reduce the amount of dependencies brought in

2025-01-31 12:36 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      return address ? parseCaipAccountId(address).address : null;
Agreed, not a problem for now but would be great to have a proper error from the keyring side

2025-01-31 12:37 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +    assert(!scope.startsWith('eip155') && !scope.startsWith('wallet:eip155'));
Can use the enum but will need a string for `wallet:eip155`. Not confident we wanna block `wallet` as a whole

2025-01-31 12:38 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      .filter((account: InternalAccount) => account.metadata.snap?.enabled)
Refactored this a bit to reduce duplication

2025-01-31 12:40 UTC, ccharly commented on packages/snaps-controllers/src/test-utils/multichain.ts
> +  'bip122:000000000019d6689c085ae165831e93' as CaipChainId;
Yup, I do agree with the `keyring-api`, having them somewhere else would be better. Thanks!

2025-01-31 13:06 UTC, danroc commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      return address ? parseCaipAccountId(address).address : null;
Yes, we should enforce it on the keyring side; it should be a small change.

Not a problem for now, but I wonder if it will ever be a problem for off-chain accounts (like EOAs). Luckily, there is the special case for EVM EOAs, but we should push CASA to propose something that's chain-agnostic.

2025-01-31 13:08 UTC, danroc commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      .call('AccountsController:listMultichainAccounts', scope)
I suppose it's time to do that `TODO` :dadjoke:

2025-01-31 13:21 UTC, danroc commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +          account.methods.includes(request.method),
Just a note: this is checked by the `SnapKeyring` before the request is submitted to the Snap, but there is no problem in keeping this check here too.

2025-01-31 13:22 UTC, FrederikBolding commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +          account.methods.includes(request.method),
It is important to have it here as we only wanna consider accounts that support the requested method

2025-01-31 13:22 UTC, Mrtenz approved these changes

2025-01-31 13:22 UTC, ccharly commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      .call('AccountsController:listMultichainAccounts', scope)
- https://github.com/MetaMask/accounts-planning/issues/820

2025-01-31 13:26 UTC, merged

2025-01-31 13:26 UTC, ccharly commented on packages/snaps-controllers/src/multichain/MultichainRouter.ts
> +      return address ? parseCaipAccountId(address).address : null;
- https://github.com/MetaMask/accounts-planning/issues/821